config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  root 'homepage#home'
  get '/signup' => 'users#new'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  resources :tasks
  resources :users

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
	validates :content,
		presence: true,
		uniqueness: true
	validates :deadline,
		presence: true
	validates :comment,
		presence: true 
end

app/models/user.rb
class User < ApplicationRecord
	before_save { self.email = email.downcase }

	validates :name, presence: true
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true,
	format: { with: VALID_EMAIL_REGEX },
	uniqueness: { case_sensitive: false }

	has_secure_password
	validates :password, presence: true, length: { minimum: 6 }

	# 渡された文字列のハッシュ値を返す
	def User.digest(string)
		cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
													  BCrypt::Engine.cost
		BCrypt::Password.create(string, cost: cost)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
	include SessionsHelper
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def home
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to use
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
	before_action :logged_in_check

	def index 
		@task = Task.all
	end

	def new
		@task = Task.new
	end

	def create 
		@task = Task.new(task_params)
		if @task.save 
			flash[:notice] = "Added new task"
			redirect_to tasks_path
		else
			render 'new'
		end
	end

	def show 
		@task = Task.find(params[:id])
	end

	def edit 
		@task = Task.find(params[:id])
	end

	def update 
		@task = Task.find(params[:id])
		if @task.update (task_params)
			flash[:notice] = "Edited a task"
			redirect_to tasks_path 
		else
			render 'edit'
		end
	end

	def destroy 
		@task = Task.find(params[:id])
		@task.destroy 
		flash[:notice] = "Destroy a task"
		redirect_to tasks_path 
	end

	private
		def task_params
			params.require(:task).permit(:content, :deadline, :done, :comment)
		end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "You logged in!"
      redirect_to tasks_url
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	# 渡されたユーザーでログインする
	def log_in(user)
		session[:user_id] = user.id
	end

	# 現在ログイン中のユーザーを返す (いる場合)
	def current_user
		if session[:user_id]
		  @current_user ||= User.find_by(id: session[:user_id])
		end
	end

	 # ユーザーがログインしていればtrue、その他ならfalseを返す
	def logged_in?
		!current_user.nil?
	end

	def logged_in_check
		redirect_to root_url if current_user.nil?
	end

	

	# 現在のユーザーをログアウトする
	def log_out
		session.delete(:user_id)
		@current_user = nil
	end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homepage/home.html.erb
<h1><%= link_to "Sign up", signup_path %></h1>
<h1><%= link_to "Log in", '#' %></h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- <%= notice %> -->
    <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <% if logged_in? %>
			<%= link_to 'Log out', logout_path(session), method: :delete, data: {confirm: 'Are you sure?'} %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/tasks/_form.html.erb
<% if task.errors.any? %>
	<div id="error_explanation">
		<h2><%= pluralize(task.errors.count, "error") %> prohibited this book from 
		being saved:</h2>

		<ul>
		<% task.errors.full_messages.each do |message| %>
			<li><%= message %></li>
		<% end %>
		</ul>
	</div>
<% end %>
<%= form_for(task) do |f| %>
	<div class="field">
		<p>
		<%= f.label :ToDo%>
		<%= f.text_field :content, size: 25 %>
		</p>
		<p>
		<%= f.label :Deadline%>
		<%= f.date_field :deadline %> 
		</p>
		<p>
		<%= f.label :Finish?%>
		<%= f.check_box :done, {class: 'cnk'} %>
		</p>
		<p>
		<%= f.label :コメント%>
		<%= f.text_field :comment, size: 25 %>
		</p>

		<%= f.submit %>
	</div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Edit todo Task</h1>
<%= render 'form', task:@task %>
<%= link_to 'return', root_path %>

app/views/tasks/index.html.erb
<h1>todoApp</h1>

<%= link_to 'Add', new_task_path %>
<div class="contents">
	<table>
		<tr>
			<th>todo task</th>
			<th>deadline</th>
			<th>finish?</th>
			<th>comment</th>
		</tr>
		<% @task.each do |task| %>
		<tr>
			<td><%= link_to task.content, task_path(task) %></td>
			<td><%= task.deadline %></td>
			<td><%= task.done %></td>
			<td><%= task.comment %></td>
			<td><%= link_to 'Edit', edit_task_path(task) %></td>
			<td><%= link_to 'Delete', task_path(task), method: :delete, data: {confirm: 'Are you sure?'} %></td>
		</tr>
		<% end %>
	</table>
	
</div>

app/views/tasks/new.html.erb
<h1>Add todo Task</h1>
<%= render 'form', task:@task %>
<%= link_to 'return', root_path %>

app/views/tasks/show.html.erb
<table>
	<tr>
		<th>todo task</th>
		<th>deadline</th>
		<th>finish?</th>
		<th>comment</th>
	</tr> 
	<tr>
		<td><%= @task.content %></td>
		<td><%= @task.deadline %></td>
		<td><%= @task.done %></td>
		<td><%= @task.comment %></td>
	</tr>
</table>

<%= link_to 'return', root_path %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<div class="row">
<%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages' %>

	<%= f.label :name %>
	<%= f.text_field :name %>

	<%= f.label :email %>
	<%= f.email_field :email %>

	<%= f.label :password %>
	<%= f.password_field :password %>

	<%= f.label :password_confirmation %>
	<%= f.password_field :password_confirmation %>

	<%= f.submit "Create my account" %>
<% end %>
</div>

app/views/users/show.html.erb
<%= @user.name %>, <%= @user.email %>